tienda_virtual/ofertas/urls.py
from django.urls import path
from . import views

app_name='ofertas'

urlpatterns = [
    path('', views.index, name='index'),
]

tienda_virtual/productos/urls.py
from django.urls import path
from . import views

app_name='productos'

urlpatterns = [
    path('', views.index, name='index'),
]

tienda_virtual/tienda_virtual/urls.py
#from django import views
from . import views  #El . indica que el archivo esta en el mismo directorio donde esta ubcado este archivo
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('productos/', include('productos.urls')),
    path('ofertas/', include('ofertas.urls')),
    path('', views.index, name='index'),
]

tienda_virtual/categoria/models.py
from django.db import models

# Create your models here.

tienda_virtual/ofertas/models.py
from django.db import models

tienda_virtual/productos/models.py
from django.db import models

class Categoria(models.Model):
    nombre = models.CharField(max_length=100)
 
    def __str__(self):
        return self.nombre
    
class Producto(models.Model):
    nombre = models.CharField(max_length=200)
    precio = models.DecimalField(max_digits=10, decimal_places=2)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
 
    def __str__(self):
        return self.nombre

tienda_virtual/categoria/views.py
from django.shortcuts import render

# Create your views here.

tienda_virtual/ofertas/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    return render(request, 'ofertas/index.html')

tienda_virtual/productos/views.py
from django.shortcuts import render
from .models import Producto

def index(request):
    productos = Producto.objects.all()
    return render(request, 'productos/index.html', {'productos': productos})

tienda_virtual/tienda_virtual/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

tienda_virtual/ofertas/templates/ofertas/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <title>Ofertas</title>
  </head>
  <body>
    <header>
      <h1>Ofertas Actuales</h1>
    </header>
    <nav>

      <a href="/">Regresar a la página principal</a>
    </nav>

    
    <p>Consulta nuestras últimas ofertas en la tienda.</p>
    <script src="{% static 'js/scripts.js' %}"></script>
  </body>
</html>

tienda_virtual/productos/templates/productos/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'css/styles.css' %}"
    />
    <title>Productos</title>
  </head>
  <body>
    <header>
      <h1>Lista de Productos</h1>
    </header>
    
    <nav>
      <a href="{% url 'index' %}">Inicio</a>
      <br />
      <a href="{% url 'ofertas:index' %}">Ofertas</a>
    </nav>
    <br />

    <div class="container">
      <table>
        <thead>
          <tr>
            <th>NOMBRE</th>
            <th>PRECIO</th>
            <th>CATEGORIA</th>
          </tr>
        </thead>
        <tbody>
          {% for producto in productos %}
          <tr>
            <td>{{ producto.nombre }}</td>
            <td>{{ producto.precio }}</td>
            <td>{{ producto.categoria.nombre }}</td>
          </tr>
          {% empty %}
          <tr>
            <td colspan="3">
              <h4>No hay productos</h4>
            </td>
          </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
    <br />
    <script src="{% static 'js/scripts.js' %}"></script>
  </body>
</html>

tienda_virtual/templates/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
    <title>Pagina Principal</title>
  </head>
  <body>
    <header>
      <h1>PAGINA PRINCIPAL</h1>
    </header>

    <nav>
      <a href="{% url 'productos:index' %}">Productos</a>
      <br />
      <a href="{% url 'ofertas:index' %}">Ofertas</a>
    </nav>

    <br />
    <div class="container">
      <button id="show-alert">Presiona Aqui</button>
    </div>
    <script src="{% static 'js/scripts.js' %}"></script>
  </body>
</html>